spring:
  data:
    redis:
      database: 3
      host: localhost
      port: 6379
#  datasource:
#    url: jdbc:mysql://localhost:3306/super?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true
#    username: root
#    password: 123
#
